name: Wait For Workflows To Succeed
author: Emil Goldsmith Olesen
description: Given a list of local workflow file names, wait for ones that were created for the same push/pull_request event to succeed
branding:
  icon: activity
  color: blue
inputs:
  wait-interval-seconds:
    description: Seconds to wait between checks
    required: true

  wait-max-seconds:
    description: Max seconds to wait in total before failing
    required: true

  repo-token:
    description: The github.token in context or GITHUB_TOKEN env variable repo token for your workflow
    required: true

  workflows:
    description: The workflows to wait for. Either specify one as a normal string or several workflows as newline separated strings with forexample the | multiline YAML syntax
    required: true

  debug:
    description: Whether or not to have debug logs show. Possible values are `on`, `off`, and `verbose`
    required: false
    default: "off"

runs:
  using: "node12"
  main: "index.js"
