on: push

jobs:
  add-to-pr:
    name: Add to the test PR for a PR event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do the add
        env:
          # Use our own custom token so that PR events actually trigger
          # which are auto disabled for avoiding recursive triggers for
          # the token provided with the workflow
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        run: |
          git config --global user.email "emil.goldsmith@gmail.com"
          git config --global user.name "Emil Goldsmith Olesen"
          git fetch origin test
          git checkout test
          echo "an addition" >> test
          git add test
          git commit -m "A commit to trigger a PR event for testing"
          git push origin test
