name: Fast Success Fixture
on:
  - push
  - pull_request

jobs:
  suceeds:
    name: Succeeds Slowly
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        shell: bash
        run: sleep 30
