name: Fast Failure Fixture
on:
  - push
  - pull_request

jobs:
  suceeds:
    name: Fails Fast
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        shell: bash
        run: sleep 10

      - name: Fail
        run: echo "Fail" && exit 1
