name: Failure Fixture
on:
  - push
  - pull_request

jobs:
  suceeds:
    name: Fails Slowly
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        shell: bash
        run: sleep 30

      - name: Fail
        run: echo "Fail" && exit 1
